# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: McGonnigal Development
email: info@McGonnigalDevelopment.com

description: > #

baseurl: "/mcgondev-jekyll"
url: "http://McGonnigalDevelopment.com"

# Build settings
markdown: kramdown

exclude: [_sass/_theme.scss, _includes/archive]

gems:
 - jekyll-coffeescript
 - jekyll-paginate
